# Generated by Django 5.2.13 on 2026-04-30 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex00', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created']},
        ),
    ]
