# Generated by Django 6.0.4 on 2026-04-18 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ex10", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="people",
            name="homeworld",
            field=models.ForeignKey(
                db_column="homeworld",
                on_delete=django.db.models.deletion.CASCADE,
                to="ex10.planets",
                to_field="name",
            ),
        ),
    ]
