[mypy]
python_version = 3.11
plugins = mypy_django_plugin.main,mypy_drf_plugin.main
strict = True
mypy_path = $MYPY_CONFIG_FILE_DIR/chanx_django
explicit_package_bases = True

[mypy.plugins.django-stubs]
django_settings_module = config.settings.base
