# Generated by Django 6.0.4 on 2026-04-18 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ex09", "0002_alter_people_homeworld"),
    ]

    operations = [
        migrations.AlterField(
            model_name="people",
            name="homeworld",
            field=models.ForeignKey(
                blank=True,
                db_column="homeworld",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ex09.planets",
            ),
        ),
    ]
