# Generated by Django 6.0.4 on 2026-04-18 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0004_alter_people_homeworld'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='homeworld',
            field=models.ForeignKey(db_column='homeworld', on_delete=django.db.models.deletion.CASCADE, to='ex09.planets', to_field='name'),
        ),
    ]
