# Generated by Django 6.0.4 on 2026-04-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ex09", "0007_alter_people_homeworld"),
    ]

    operations = [
        migrations.AlterField(
            model_name="people",
            name="name",
            field=models.CharField(max_length=64),
        ),
    ]
