# Generated by Django 5.2.13 on 2026-08-09 17:50

from django.db import migrations

def create_initial_rooms(apps, schema_editor):
    Room = apps.get_model("chat", "Room")
    initial_rooms = ["General", "Random", "Tech"]
    for room_name in initial_rooms:
        Room.objects.get_or_create(name=room_name)


def remove_initial_rooms(apps, schema_editor):
    Room = apps.get_model("chat", "Room")
    Room.objects.filter(name__in=["General", "Random", "Tech"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_rooms, remove_initial_rooms),
    ]
