# Generated by Django 5.2.13 on 2026-04-23 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_tip_hide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tip',
            options={'permissions': [('can_downvote_tips', 'Can downvote any tip')]},
        ),
    ]
