# Generated by Django 5.2.13 on 2026-04-23 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0005_alter_tip_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="reputation",
        ),
    ]
