# Generated by Django 5.2.13 on 2026-04-23 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0006_remove_user_reputation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tip",
            name="hide",
        ),
    ]
